vim.g.mapleader = " ";
vim.wo.number = true;
vim.wo.relativenumber = true;
vim.wo.signcolumn = 'no';
vim.cmd("syntax off");
vim.cmd("set smartindent");
vim.cmd("set mouse=");
vim.bo.tabstop = 4;
vim.bo.softtabstop = 4;
vim.bo.shiftwidth = 4;
vim.keymap.set("n", "<leader>pv", vim.cmd.Ex);
vim.keymap.set("n", "<F12>", vim.cmd.EslintFixAll);
